cameras:
  - id: mendeleeva_130_cam_9
    map_url: http://maps.ufanet.ru/ufa#1549441947OXE898
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: upper_7
        box: 0.031,0.333,0.129,0.675
        angle: -16.0
      - id: slot_1
        box: 0.402,0.739,0.480,0.988
        angle: -30.0
      - id: slot_2
        box: 0.538,0.279,0.593,0.504
        angle: -38.0
      - id: slot_3
        box: 0.492,0.284,0.546,0.509
        angle: -38.0
      - id: slot_4
        box: 0.435,0.264,0.488,0.501
        angle: -36.0
      - id: slot_5
        box: 0.386,0.300,0.440,0.537
        angle: -34.0
      - id: slot_6
        box: 0.328,0.308,0.381,0.545
        angle: -34.0
      - id: slot_7
        box: 0.265,0.319,0.338,0.593
        angle: -27.0
      - id: slot_8
        box: 0.194,0.333,0.270,0.610
        angle: -23.0
      - id: slot_9
        box: 0.121,0.345,0.206,0.645
        angle: -21.0
      - id: slot_10
        box: 0.593,0.314,0.648,0.524
        angle: -38.0
      - id: slot_12
        box: 0.501,0.689,0.565,1.000
        angle: -35.0
      - id: slot_13
        box: 0.543,0.627,0.607,0.938
        angle: -35.0
      - id: slot_14
        box: 0.596,0.606,0.648,0.930
        angle: -35.0
      - id: slot_15
        box: 0.645,0.606,0.690,0.879
        angle: -35.0
      - id: slot_16
        box: 0.677,0.585,0.717,0.787
        angle: -36.0
      - id: slot_17
        box: 0.708,0.560,0.756,0.740
        angle: -38.0
      - id: slot_18
        box: 0.748,0.511,0.790,0.694
        angle: -38.0
      - id: slot_19
        box: 0.782,0.472,0.820,0.656
        angle: -38.0
      - id: slot_20
        box: 0.815,0.435,0.853,0.619
        angle: -38.0
      - id: slot_21
        box: 0.809,0.289,0.831,0.397
        angle: -34.0
      - id: slot_11
        box: 0.851,0.426,0.882,0.612
        angle: -35.0
      - id: slot_22
        box: 0.910,0.364,0.935,0.434
        angle: 52.0
      - id: slot_23
        box: 0.834,0.282,0.856,0.387
        angle: -34.0
      - id: slot_24
        box: 0.864,0.281,0.884,0.395
        angle: -34.0
      - id: slot_25
        box: 0.886,0.279,0.909,0.377
        angle: -34.0
      - id: slot_26
        box: 0.940,0.430,0.965,0.500
        angle: 52.0
      - id: slot_27
        box: 0.929,0.401,0.954,0.471
        angle: 52.0
    stable_cycles: 2

  - id: mendeleeva_130_cam_5
    map_url: http://maps.ufanet.ru/ufa#1549441947OXE841
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: upper_1
        box: 0.584,0.251,0.651,0.535
        angle: 65.0
      - id: slot_1
        box: 0.501,0.000,0.549,0.281
        angle: 67.0
      - id: slot_2
        box: 0.536,0.059,0.584,0.341
        angle: 67.0
      - id: slot_3
        box: 0.553,0.145,0.619,0.430
        angle: 65.0
      - id: slot_5
        box: 0.617,0.349,0.694,0.658
        angle: 65.0
      - id: slot_4
        box: 0.670,0.441,0.770,0.805
        angle: 61.0
      - id: slot_7
        box: 0.718,0.601,0.818,0.965
        angle: 61.0
      - id: slot_8
        box: 0.893,0.139,0.959,0.387
        angle: 57.0
      - id: slot_9
        box: 0.852,0.042,0.919,0.290
        angle: 57.0
    stable_cycles: 2

  - id: salavat_square
    map_url: http://maps.ufanet.ru/ufa#001-999-011
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    detection_roi: 0.28,0.17,0.95,0.63
    detection_exclude_rois:
      - 0.82,0.10,1.00,0.34
    stable_cycles: 2

  - id: sports_palace_square
    map_url: http://maps.ufanet.ru/ufa#001-999-054
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    detection_roi: 0.00,0.18,0.24,0.66
    stable_cycles: 2

  - id: park_pobedy
    map_url: http://maps.ufanet.ru/ufa#001-998-001-005
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    detection_roi: 0.76,0.04,0.99,0.30
    stable_cycles: 2

  - id: ufa_arena_1
    map_url: http://maps.ufanet.ru/ufa#001-999-157
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: gate_row_3
        box: 0.379,0.333,0.399,0.384
        angle: 1.0
      - id: slot_1
        box: 0.359,0.339,0.379,0.390
        angle: 1.0
      - id: slot_2
        box: 0.398,0.336,0.418,0.387
        angle: -3.0
      - id: slot_3
        box: 0.510,0.533,0.551,0.693
        angle: -93.0
      - id: slot_4
        box: 0.419,0.331,0.440,0.381
        angle: -7.0
      - id: slot_5
        box: 0.441,0.327,0.461,0.378
        angle: -15.0
      - id: slot_6
        box: 0.461,0.325,0.481,0.376
        angle: -18.0
      - id: slot_7
        box: 0.481,0.319,0.502,0.370
        angle: -27.0
      - id: slot_8
        box: 0.505,0.322,0.526,0.379
        angle: -34.0
      - id: slot_9
        box: 0.528,0.319,0.545,0.376
        angle: -40.0
      - id: slot_10
        box: 0.549,0.318,0.566,0.377
        angle: -40.0
      - id: slot_11
        box: 0.569,0.317,0.586,0.380
        angle: -37.0
      - id: slot_12
        box: 0.347,0.381,0.366,0.435
        angle: 3.0
      - id: slot_14
        box: 0.367,0.383,0.386,0.438
        angle: 3.0
      - id: slot_15
        box: 0.384,0.384,0.404,0.439
        angle: -1.0
      - id: slot_16
        box: 0.448,0.374,0.475,0.430
        angle: -18.0
      - id: slot_17
        box: 0.474,0.373,0.500,0.431
        angle: -22.0
      - id: slot_18
        box: 0.499,0.371,0.525,0.430
        angle: -34.0
      - id: slot_19
        box: 0.403,0.382,0.424,0.439
        angle: -2.0
      - id: slot_20
        box: 0.423,0.381,0.449,0.439
        angle: -2.0
      - id: slot_21
        box: 0.597,0.521,0.637,0.681
        angle: -93.0
      - id: slot_22
        box: 0.680,0.508,0.720,0.668
        angle: -93.0
      - id: slot_23
        box: 0.760,0.511,0.799,0.644
        angle: -93.0
      - id: slot_24
        box: 0.827,0.508,0.863,0.623
        angle: -98.0
      - id: slot_25
        box: 0.886,0.501,0.922,0.603
        angle: -98.0
      - id: slot_26
        box: 0.944,0.487,0.980,0.589
        angle: -98.0
    stable_cycles: 2

  - id: kirova_parhomenko
    map_url: http://maps.ufanet.ru/ufa#001-999-119
    enabled: false
    source_transport: hls
    min_confidence: 0.05
    stable_cycles: 2

  - id: mushnikova_balandina
    map_url: http://maps.ufanet.ru/ufa#001-999-098
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: far_1
        box: 0.591,0.438,0.613,0.521
        angle: -56.0
      - id: slot_1
        box: 0.626,0.404,0.649,0.506
        angle: -59.0
      - id: slot_3
        box: 0.569,0.450,0.591,0.533
        angle: -54.0
      - id: slot_4
        box: 0.551,0.456,0.575,0.551
        angle: -53.0
      - id: slot_5
        box: 0.530,0.475,0.555,0.569
        angle: -51.0
      - id: slot_6
        box: 0.509,0.502,0.534,0.596
        angle: -49.0
      - id: slot_7
        box: 0.488,0.526,0.513,0.614
        angle: -45.0
      - id: slot_8
        box: 0.472,0.544,0.496,0.638
        angle: -41.0
      - id: slot_9
        box: 0.454,0.560,0.475,0.644
        angle: -41.0
      - id: slot_10
        box: 0.426,0.587,0.455,0.656
        angle: -37.0
      - id: slot_11
        box: 0.492,0.622,0.528,0.751
        angle: -43.0
      - id: slot_14
        box: 0.549,0.600,0.572,0.697
        angle: -43.0
      - id: slot_15
        box: 0.527,0.612,0.556,0.719
        angle: -43.0
      - id: slot_16
        box: 0.566,0.581,0.588,0.680
        angle: -43.0
      - id: slot_17
        box: 0.595,0.576,0.620,0.667
        angle: -49.0
      - id: slot_18
        box: 0.618,0.551,0.643,0.642
        angle: -47.0
      - id: slot_19
        box: 0.644,0.542,0.666,0.614
        angle: -46.0
      - id: slot_20
        box: 0.682,0.531,0.708,0.638
        angle: -52.0
      - id: slot_21
        box: 0.701,0.514,0.726,0.620
        angle: -52.0
      - id: slot_22
        box: 0.719,0.498,0.745,0.605
        angle: -52.0
      - id: slot_23
        box: 0.736,0.481,0.762,0.587
        angle: -49.0
    stable_cycles: 2

  - id: lesotehnikuma_luganskaya
    map_url: http://maps.ufanet.ru/ufa#001-999-139
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: lower_row_2
        box: 0.078,0.875,0.153,0.923
        angle: -2.0
      - id: slot_1
        box: 0.061,0.898,0.136,0.946
        angle: -5.0
      - id: slot_2
        box: 0.110,0.846,0.188,0.884
      - id: slot_3
        box: 0.151,0.808,0.223,0.856
        angle: -3.0
      - id: slot_4
        box: 0.179,0.788,0.240,0.833
        angle: -3.0
      - id: slot_5
        box: 0.207,0.762,0.268,0.807
        angle: -3.0
      - id: slot_6
        box: 0.219,0.740,0.280,0.785
        angle: -3.0
      - id: slot_7
        box: 0.231,0.726,0.292,0.771
        angle: -3.0
      - id: slot_8
        box: 0.246,0.711,0.307,0.756
        angle: -3.0
      - id: slot_9
        box: 0.263,0.689,0.323,0.734
        angle: -3.0
      - id: slot_10
        box: 0.143,0.731,0.187,0.779
        angle: -41.0
      - id: slot_11
        box: 0.104,0.718,0.151,0.769
        angle: -44.0
      - id: slot_12
        box: 0.084,0.711,0.128,0.754
        angle: -44.0
      - id: slot_13
        box: 0.049,0.703,0.097,0.747
        angle: -36.0
      - id: slot_14
        box: 0.022,0.691,0.070,0.735
        angle: -36.0
      - id: slot_15
        box: 0.000,0.688,0.040,0.731
        angle: -41.0
      - id: slot_16
        box: 0.179,0.694,0.218,0.733
        angle: -31.0
      - id: slot_24
        box: 0.234,0.644,0.268,0.684
        angle: -42.0
      - id: slot_25
        box: 0.207,0.645,0.242,0.686
        angle: -42.0
      - id: slot_26
        box: 0.181,0.641,0.218,0.680
        angle: -42.0
      - id: slot_28
        box: 0.165,0.644,0.203,0.685
        angle: -42.0
      - id: slot_29
        box: 0.144,0.628,0.182,0.667
        angle: -42.0
      - id: slot_30
        box: 0.119,0.616,0.157,0.655
        angle: -42.0
      - id: slot_31
        box: 0.098,0.627,0.132,0.656
        angle: -42.0
      - id: slot_27
        box: 0.081,0.622,0.115,0.651
        angle: -42.0
      - id: slot_33
        box: 0.063,0.614,0.097,0.643
        angle: -42.0
      - id: slot_34
        box: 0.043,0.611,0.077,0.640
        angle: -42.0
      - id: slot_35
        box: 0.023,0.606,0.057,0.635
        angle: -42.0
      - id: slot_36
        box: 0.003,0.603,0.036,0.631
        angle: -42.0
      - id: slot_17
        box: 0.032,0.764,0.094,0.819
        angle: 18.0
    stable_cycles: 2

  - id: zaki_validi_aksakova
    map_url: http://maps.ufanet.ru/ufa#001-999-111
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: slot_1
        box: 0.590,0.312,0.613,0.388
        angle: -41.0
      - id: slot_3
        box: 0.571,0.337,0.594,0.413
        angle: -41.0
      - id: slot_4
        box: 0.609,0.304,0.628,0.378
        angle: -41.0
      - id: slot_6
        box: 0.627,0.290,0.649,0.373
        angle: -41.0
      - id: slot_7
        box: 0.641,0.279,0.663,0.362
        angle: -45.0
      - id: slot_8
        box: 0.658,0.269,0.680,0.352
        angle: -45.0
      - id: slot_9
        box: 0.674,0.257,0.694,0.337
        angle: -45.0
      - id: slot_5
        box: 0.691,0.249,0.711,0.329
        angle: -45.0
      - id: slot_10
        box: 0.707,0.241,0.727,0.320
        angle: -45.0
      - id: slot_11
        box: 0.720,0.239,0.736,0.310
        angle: -47.0
      - id: slot_12
        box: 0.733,0.233,0.752,0.306
        angle: -47.0
      - id: slot_13
        box: 0.749,0.230,0.768,0.304
        angle: -47.0
      - id: slot_14
        box: 0.763,0.220,0.782,0.294
        angle: -47.0
    stable_cycles: 2

  - id: bakalinskaya_27_vk6
    map_url: http://maps.ufanet.ru/ufa#1558354706LVS590
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: slot_1
        box: 0.543,0.727,0.620,1.000
        angle: 21.0
      - id: slot_2
        box: 0.478,0.681,0.553,0.971
        angle: 25.0
      - id: slot_3
        box: 0.408,0.638,0.483,0.928
        angle: 25.0
      - id: slot_4
        box: 0.343,0.601,0.418,0.891
        angle: 30.0
      - id: slot_5
        box: 0.266,0.544,0.356,0.834
        angle: 35.0
      - id: slot_6
        box: 0.241,0.462,0.299,0.747
        angle: 71.0
      - id: slot_7
        box: 0.246,0.423,0.287,0.682
        angle: 73.0
      - id: slot_8
        box: 0.242,0.368,0.277,0.610
        angle: 76.0
      - id: slot_9
        box: 0.239,0.319,0.269,0.565
        angle: 74.0
      - id: slot_10
        box: 0.239,0.279,0.266,0.518
        angle: 75.0
      - id: slot_11
        box: 0.460,0.279,0.504,0.442
        angle: 35.0
      - id: slot_12
        box: 0.226,0.259,0.254,0.468
        angle: 75.0
      - id: slot_13
        box: 0.223,0.218,0.252,0.426
        angle: 77.0
      - id: slot_14
        box: 0.216,0.196,0.241,0.374
        angle: 76.0
      - id: slot_15
        box: 0.211,0.162,0.236,0.331
        angle: 78.0
      - id: slot_20
        box: 0.506,0.295,0.549,0.458
        angle: 32.0
      - id: slot_21
        box: 0.548,0.321,0.592,0.484
        angle: 28.0
      - id: slot_22
        box: 0.588,0.342,0.637,0.507
        angle: 22.0
      - id: slot_23
        box: 0.633,0.372,0.682,0.538
        angle: 17.0
      - id: slot_24
        box: 0.677,0.397,0.727,0.563
        angle: 9.0
      - id: slot_25
        box: 0.721,0.418,0.771,0.583
        angle: 5.0
      - id: slot_26
        box: 0.770,0.431,0.820,0.597
        angle: 2.0
      - id: slot_29
        box: 0.416,0.186,0.444,0.300
        angle: 45.0
      - id: slot_30
        box: 0.480,0.194,0.515,0.318
        angle: 42.0
      - id: slot_27
        box: 0.514,0.207,0.548,0.331
        angle: 37.0
      - id: slot_32
        box: 0.623,0.262,0.659,0.356
        angle: 20.0
      - id: slot_33
        box: 0.658,0.279,0.693,0.373
        angle: 17.0
      - id: slot_34
        box: 0.693,0.298,0.729,0.393
        angle: 11.0
      - id: slot_31
        box: 0.727,0.315,0.762,0.409
        angle: 6.0
      - id: slot_35
        box: 0.764,0.332,0.799,0.427
        angle: -3.0
      - id: slot_36
        box: 0.795,0.352,0.830,0.441
        angle: -9.0
      - id: slot_37
        box: 0.826,0.356,0.860,0.445
        angle: -9.0
      - id: slot_38
        box: 0.456,0.122,0.491,0.211
        angle: 46.0
      - id: slot_40
        box: 0.484,0.131,0.518,0.220
        angle: 46.0
      - id: slot_41
        box: 0.514,0.141,0.548,0.230
        angle: 46.0
      - id: slot_42
        box: 0.548,0.144,0.582,0.232
        angle: 37.0
      - id: slot_43
        box: 0.622,0.156,0.652,0.219
        angle: 27.0
      - id: slot_44
        box: 0.643,0.194,0.672,0.264
        angle: 22.0
      - id: slot_45
        box: 0.679,0.176,0.708,0.245
        angle: 18.0
      - id: slot_46
        box: 0.702,0.219,0.732,0.306
        angle: 6.0
      - id: slot_47
        box: 0.732,0.241,0.761,0.319
      - id: slot_48
        box: 0.763,0.264,0.792,0.333
        angle: -3.0
      - id: slot_49
        box: 0.789,0.277,0.818,0.346
        angle: -6.0
      - id: slot_50
        box: 0.813,0.287,0.842,0.356
        angle: -6.0
      - id: slot_52
        box: 0.848,0.306,0.877,0.376
        angle: -17.0
      - id: slot_53
        box: 0.650,0.162,0.679,0.231
        angle: 22.0
      - id: slot_54
        box: 0.673,0.211,0.702,0.281
        angle: 18.0
      - id: slot_55
        box: 0.704,0.190,0.733,0.259
        angle: 11.0
      - id: slot_56
        box: 0.729,0.204,0.758,0.273
        angle: 6.0
      - id: slot_57
        box: 0.756,0.216,0.785,0.285
        angle: -4.0
      - id: slot_58
        box: 0.778,0.225,0.807,0.294
        angle: -5.0
      - id: slot_59
        box: 0.808,0.244,0.832,0.312
        angle: -15.0
      - id: slot_60
        box: 0.838,0.264,0.867,0.333
        angle: -12.0
      - id: slot_28
        box: 0.458,0.199,0.486,0.313
        angle: 45.0
      - id: slot_39
        box: 0.311,0.087,0.341,0.186
        angle: 51.0
      - id: slot_51
        box: 0.357,0.091,0.385,0.185
        angle: 45.0
      - id: slot_61
        box: 0.383,0.105,0.411,0.199
        angle: 45.0
    stable_cycles: 2

  - id: bakalinskaya_27_vk7
    map_url: http://maps.ufanet.ru/ufa#1558354706LVS615
    source_transport: hls
    min_confidence: 0.05
    detection_image_size: 1280
    parking_slots:
      - id: bottom_right_1
        box: 0.052,0.617,0.149,0.961
        angle: -23.0
      - id: slot_1
        box: 0.115,0.541,0.212,0.885
        angle: -23.0
      - id: slot_2
        box: 0.000,0.085,0.074,0.286
      - id: slot_3
        box: 0.284,0.527,0.413,0.892
        angle: 12.0
      - id: slot_4
        box: 0.406,0.549,0.531,0.942
        angle: 8.0
      - id: slot_5
        box: 0.525,0.594,0.646,0.972
        angle: 4.0
      - id: slot_6
        box: 0.637,0.623,0.736,0.997
        angle: 1.0
      - id: slot_7
        box: 0.725,0.643,0.815,1.000
        angle: -2.0
      - id: slot_8
        box: 0.805,0.715,0.859,1.000
        angle: -2.0
      - id: slot_9
        box: 0.854,0.736,0.898,1.000
        angle: -5.0
      - id: slot_10
        box: 0.889,0.736,0.934,1.000
        angle: -5.0
      - id: slot_11
        box: 0.928,0.767,0.962,1.000
        angle: -5.0
      - id: slot_12
        box: 0.957,0.763,0.998,0.999
      - id: slot_14
        box: 0.664,0.159,0.694,0.322
        angle: -40.0
      - id: slot_15
        box: 0.702,0.153,0.727,0.329
        angle: -43.0
      - id: slot_16
        box: 0.727,0.138,0.753,0.322
        angle: -43.0
      - id: slot_17
        box: 0.759,0.137,0.780,0.320
        angle: -42.0
      - id: slot_18
        box: 0.821,0.141,0.840,0.283
        angle: -42.0
      - id: slot_19
        box: 0.846,0.137,0.865,0.278
        angle: -42.0
      - id: slot_20
        box: 0.871,0.137,0.891,0.278
        angle: -42.0
      - id: slot_21
        box: 0.895,0.127,0.914,0.269
        angle: -42.0
      - id: slot_23
        box: 0.866,0.386,0.895,0.565
        angle: -37.0
      - id: slot_24
        box: 0.889,0.360,0.911,0.541
        angle: -38.0
      - id: slot_25
        box: 0.903,0.339,0.923,0.519
        angle: -38.0
      - id: slot_26
        box: 0.915,0.323,0.936,0.503
        angle: -38.0
      - id: slot_27
        box: 0.926,0.292,0.947,0.473
        angle: -38.0
      - id: slot_28
        box: 0.945,0.273,0.965,0.453
        angle: -38.0
      - id: slot_29
        box: 0.213,0.556,0.323,0.898
        angle: -6.0
      - id: slot_30
        box: 0.067,0.062,0.127,0.267
        angle: -7.0
      - id: slot_31
        box: 0.118,0.035,0.177,0.240
        angle: -13.0
      - id: slot_32
        box: 0.175,0.016,0.227,0.203
        angle: -15.0
      - id: slot_33
        box: 0.225,0.006,0.277,0.192
        angle: -15.0
      - id: slot_34
        box: 0.639,0.036,0.669,0.199
        angle: -40.0
      - id: slot_35
        box: 0.698,0.023,0.722,0.179
        angle: -40.0
      - id: slot_36
        box: 0.673,0.036,0.698,0.192
        angle: -43.0
    stable_cycles: 2
